# Generated by Django 5.0.2 on 2025-10-29 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_hi', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='MGNREGAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('employment_provided', models.IntegerField(default=0)),
                ('payments_on_time', models.FloatField(default=0.0)),
                ('avg_payment_delay_days', models.FloatField(default=0.0)),
                ('active_projects', models.IntegerField(default=0)),
                ('grievances_open', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mgnrega_records', to='dashboard.district')),
            ],
            options={
                'ordering': ['-month', 'district'],
                'unique_together': {('district', 'month')},
            },
        ),
    ]
